# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:

- script: |
    export COLLECTION_DIR=$(pwd)
    docker run -v $COLLECTION_DIR:/etc/newman -t postman/newman_ubuntu1404 run "DBapiClient.postman_collection.json" --environment="apitestExtClient.postman_environment.json" --reporters="junit,cli" --reporter-junit-export="newman-report.xml"
  displayName: 'Run api tests'

